### PR TITLE
fix(statically-loading) Use OpaqueToken for providing config

### PR DESCRIPTION
**Pull request by hypery2k**
see #15

### CODE REVIEW

**Comment by ls-spavel** [comment]
@hypery2k: I am trying to pull down your changes and get them to work in my project. I noticed in the readme you updated the `forRoot` to work a little differently:

```TS
TNSFontIconModule.forRoot({
     fonts: {
          provide: TranslateLoader,
          useFactory: (icons)
     }
})
```

Is it still usable like this:
```TS
TNSFontIconModule.forRoot({
     'zmdi': 'material-design-iconic-font.css'
})
```

If not, where do I import `TranslateLoader` from and why the change?

**Comment by NathanWalker** [comment]
Thank you @hypery2k very much! I'll bump and release this in a moment.
I'm not crazy about the `USE_STORE` token - not sure that's absolutely needed?

**Comment by hypery2k** [comment]
I don't think we need the token, but the ngc compile is needed due to the needed metadata

**Comment by hypery2k** [comment]
the token is needed and the ngc compile is needed. Should I make a new PR and a PR for #22?
Would be easier to verify for other

**Comment by NathanWalker** [comment]
Thanks @hypery2k ok cool yes that would be greatly appreciated. I was having trouble with the previous PR, ended up having to strip it back.

**Pull request merged**
