### PR TITLE
Fix CI build

### PR DESCRIPTION
**Pull request by hypery2k**
references.d was missing see [here](https://martinreinhardt-online.de/jenkins/job/NPM/job/nativescript-ngx-fonticon/job/master/1/) for more details.

You also add a Jenkins (GitHub plugin) service as for travis. The URL to use would be: 

https://martinreinhardt-online.de/jenkins/github-webhook/

### CODE REVIEW

**Comment by NathanWalker** [comment]
Thank you.

**Comment by hypery2k** [comment]
the [build](https://martinreinhardt-online.de/jenkins/job/NPM/job/nativescript-ngx-fonticon/job/master/2/console) works and if you allow me to publish we could get an @next version ;)

**Comment by NathanWalker** [comment]
@hypery2k just added you as contributor here as well as publisher on npm. Really appreciate all your help 👍  If anything majorly breaking change in future, just run by me via PR. Feel free to setup `@next` version on publish a new version though!

**Comment by hypery2k** [comment]
Thanks, just kicked off a build and will later setup GitHub trigger.

**Pull request merged**
