### PR TITLE
Use angular compiler to generate metadata

### PR DESCRIPTION
**Pull request by hypery2k**
see #15

### CODE REVIEW

**Comment by NathanWalker** [comment]
Why add another sample app? There's already the demo app here:
https://github.com/NathanWalker/nativescript-ngx-fonticon/tree/master/src
We could replace that one with the latest setup since it includes the Webpack files but I don't understand why you would want or need 2 sample apps? Plus the sample you have here only sets up the go tick module but has no view that actually uses it?

**Review by NathanWalker — DISMISSED** [review]
Why add another sample app? There's already the demo app here:
https://github.com/NathanWalker/nativescript-ngx-fonticon/tree/master/src
We could replace that one with the latest setup since it includes the Webpack files but I don't understand why you would want or need 2 sample apps? Plus the sample you have here only sets up the font icon module in the root module but has no view that actually uses it?

**Comment by hypery2k** [comment]
I just not wanted to complicate the demo app.
For now it's okay with the second app, as I can reproduce the issue there. 
Before merging all of this, let's discuss what and how we merge it, ok?

The PR ist still WIP

**Comment by hypery2k** [comment]
the latest commit seems to work so far with AoT enabled.
@NathanWalker We need the compiler-cli *and* USE_STORE OpaqueToken to make it work. Regarding the sample app: To verify that's all working I need to complete decoupled ng2-nativescript app with AoT enabled. So sadly to say, we need a second one, but I would like to move it to test-feeder. Would this be ok for you? If you have any further questions you'll reach we in the nativescript slack

**Comment by NathanWalker** [comment]
@hypery2k does this PR contain fixes you feel provide AoT ability?

**Comment by hypery2k** [comment]
I've verified it's working in two of my TNS projects and also some users reported it's working as it is

**Comment by hypery2k** [comment]
@NathanWalker Some Metadata was ignored in npmignore which leads besides the closures to issues. I've verified that with my latest changes it's working. Should I make release?

**Comment by hypery2k** [comment]
@NathanWalker The latest changes seems to work as in #15 mentioned. Should I make a minor release or do you want to purge and release?

**Comment by hypery2k** [comment]
@NathanWalker: Should I make a new release? it seems to work without and with AoT now, see https://github.com/NathanWalker/nativescript-ngx-fonticon/issues/15#issuecomment-295252875

**Pull request merged**
